// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okfvxtihxwxfmltzjnwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZnZ4dGloeHd4Zm1sdHpqbndlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTg5MjIsImV4cCI6MjA3MTU3NDkyMn0.QuoFm8Lyg-el3sYK62mOlwlgOb4XSSZjO1MB4zOrCT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});